name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish .NET Core Project
      run: dotnet publish -c Release -o release --nologo
    - name: Change base-tag in index.html from / to GitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorApp0\/" \/>/g' release/wwwroot/index.html
    - name: Automatic Releases
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: release/wwwroot
        tag_name: v0.1.0
